// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/434d7ebc70de28abfbd161b41f070efc8b2415c4/escape-html/escape-html.d.ts
declare module "escape-html" {
  function escapeHTML(text: string): string;
  namespace escapeHTML {}

  export = escapeHTML;
}
